#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tutort.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class=""no-js lt-ie9 lt-ie8 lt-ie7""> <![endif]-->
<!--[if IE 7]>         <html class=""no-js lt-ie9 lt-ie8""> <![endif]-->
<!--[if IE 8]>         <html class=""no-js lt-ie9""> <![endif]-->
<!--[if gt IE 8]><!-->
<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <title>");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
      Write(Tutort.Web.Localization.General.Name);

            
            #line default
            #line hidden
WriteLiteral(" | ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
                                              Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" href=\'//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic," +
"700italic,800italic,400,300,600,700,800\'");

WriteLiteral(" rel=\'stylesheet\'");

WriteLiteral(" type=\'text/css\'");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/bundles/content"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!-- Add local styles, mostly for plugins css file -->\r\n");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
     if (IsSectionDefined("Styles"))
    {
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("Styles", required: false));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
                                                 
    }

            
            #line default
            #line hidden
WriteLiteral(@"
</head>
<body>
    <!--[if lt IE 7]>
        <p class=""chromeframe"">You are using an outdated browser. <a href=""http://browsehappy.com/"">Upgrade your browser today</a> or <a href=""http://www.google.com/chromeframe/?redirect=true"">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->
    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Action("Header", "Page"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("HeadLine", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Slider", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Action("Footer", "Page"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/main/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
