#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tutort.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/LatestBlog.cshtml")]
    public partial class _Views_Shared_LatestBlog_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_LatestBlog_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"latest-blog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n                    <h2>Latest blog posts</h2>\r\n                    <img");

WriteLiteral(" src=\"images/under-heading.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost1.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">Summer Sandwich</a></h4>\r\n                            <span>29 Sep 2084</span>\r\n" +
"                        </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost2.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">New Great Taste</a></h4>\r\n                            <span>23 Sep 2084</span>\r\n" +
"                        </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost3.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">Spicy Pizza</a></h4>\r\n                            <span>14 Sep 2084</span>\r\n    " +
"                    </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost4.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">Healthy Food</a></h4>\r\n                            <span>25 Aug 2084</span>\r\n   " +
"                     </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost5.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">Great Breakfast</a></h4>\r\n                            <span>17 Aug 2084</span>\r\n" +
"                        </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"blog-thumb\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"images/blogpost6.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"blog-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content-show\"");

WriteLiteral(">\r\n                            <h4><a");

WriteLiteral(" href=\"single-post.html\"");

WriteLiteral(">Fresh Fruit Juice</a></h4>\r\n                            <span>12 Aug 2084</span>" +
"\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"content-hide\"");

WriteLiteral(@">
                            <p>Sed egestas tincidunt mollis. Suspendisse rhoncus vitae enim et faucibus. Ut dignissim nec arcu nec hendrerit. Sed arcu odio, sagittis vel diam in, malesuada malesuada risus. Aenean a sem leo. Nam ultricies dolor et mi tempor, non pulvinar felis sollicitudin.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
");

        }
    }
}
#pragma warning restore 1591
