#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tutort.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Giveaway/Giveaway.cshtml")]
    public partial class _Views_Giveaway_Giveaway_cshtml : System.Web.Mvc.WebViewPage<Tutort.Web.ViewModels.Giveaway.GiveawayViewModel>
    {
        public _Views_Giveaway_Giveaway_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Giveaway\Giveaway.cshtml"
  
    ViewBag.Title = Tutort.Web.Localization.Giveaway.Giveaway_Title;
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("HeadLine", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Giveaway\Giveaway.cshtml"
Write(Html.Partial("~/Views/Page/HeadLine.cshtml", Model.HeadLine));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n\r\n");

            
            #line 13 "..\..\Views\Giveaway\Giveaway.cshtml"
 if (!Model.IsActive)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"timeline-post\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n                        <h2>Розыгрыш завершен</h2>\r\n                        <i" +
"mg");

WriteAttribute("src", Tuple.Create(" src=\"", 572), Tuple.Create("\"", 620)
            
            #line 21 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 578), Tuple.Create<System.Object, System.Int32>(Url.Content("~/images/under-heading.png")
            
            #line default
            #line hidden
, 578), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Giveaway\Giveaway.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Giveaway\Giveaway.cshtml"
                         if (Model.Winner != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <h2><a");

WriteAttribute("href", Tuple.Create(" href=\"", 744), Tuple.Create("\"", 805)
, Tuple.Create(Tuple.Create("", 751), Tuple.Create("https://www.instagram.com/", 751), true)
            
            #line 24 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 777), Tuple.Create<System.Object, System.Int32>(Model.Winner.InstagramUser
            
            #line default
            #line hidden
, 777), false)
, Tuple.Create(Tuple.Create("", 804), Tuple.Create("/", 804), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Giveaway\Giveaway.cshtml"
                                                                                                            Write(Model.Winner.InstagramUser);

            
            #line default
            #line hidden
WriteLiteral("</a></h2>\r\n");

WriteLiteral("                            <img");

WriteLiteral(" src=\"images/under-heading.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                            <p>\r\n                                Комментарий:<br " +
"/>\r\n");

WriteLiteral("                                ");

            
            #line 28 "..\..\Views\Giveaway\Giveaway.cshtml"
                           Write(Model.Winner.Comments[0].Comment);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </p>\r\n");

            
            #line 30 "..\..\Views\Giveaway\Giveaway.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n    </div>\r\n");

            
            #line 36 "..\..\Views\Giveaway\Giveaway.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"services\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n                    <h2>Условия розыгрыша</h2>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1485), Tuple.Create("\"", 1533)
            
            #line 44 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 1491), Tuple.Create<System.Object, System.Int32>(Url.Content("~/images/under-heading.png")
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 49 "..\..\Views\Giveaway\Giveaway.cshtml"
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Giveaway\Giveaway.cshtml"
             foreach (var rule in Model.Rules)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-md-4 col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"service-item\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"icon\"");

WriteLiteral(">\r\n                            <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1865), Tuple.Create("\"", 1884)
            
            #line 54 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 1873), Tuple.Create<System.Object, System.Int32>(rule.Class
            
            #line default
            #line hidden
, 1873), false)
);

WriteLiteral("></i>\r\n                        </div>\r\n                        <h4>");

            
            #line 56 "..\..\Views\Giveaway\Giveaway.cshtml"
                       Write(rule.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                        <p>");

            
            #line 57 "..\..\Views\Giveaway\Giveaway.cshtml"
                      Write(rule.Text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 60 "..\..\Views\Giveaway\Giveaway.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"space50\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                <h3>Правила розыгрыша</h3>\r\n                <p>\r\n");

WriteLiteral("                    ");

            
            #line 69 "..\..\Views\Giveaway\Giveaway.cshtml"
               Write(Model.Info);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                <h3>Результаты розыгрыша</h3>\r\n                <p>\r\n");

WriteLiteral("                    ");

            
            #line 75 "..\..\Views\Giveaway\Giveaway.cshtml"
               Write(Model.Details);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r" +
"\n<div");

WriteLiteral(" id=\"our-team\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n                    <h2>Текущие результаты</h2>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2794), Tuple.Create("\"", 2842)
            
            #line 88 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 2800), Tuple.Create<System.Object, System.Int32>(Url.Content("~/images/under-heading.png")
            
            #line default
            #line hidden
, 2800), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Пользователь </th>
                            <th>Количество комментариев</th>
                            <th>Комментарии</th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 104 "..\..\Views\Giveaway\Giveaway.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 104 "..\..\Views\Giveaway\Giveaway.cshtml"
                          int i = 1;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 105 "..\..\Views\Giveaway\Giveaway.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Giveaway\Giveaway.cshtml"
                         foreach (var item in Model.Participants)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 108 "..\..\Views\Giveaway\Giveaway.cshtml"
                               Write(i);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3640), Tuple.Create("\"", 3693)
, Tuple.Create(Tuple.Create("", 3647), Tuple.Create("https://www.instagram.com/", 3647), true)
            
            #line 109 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 3673), Tuple.Create<System.Object, System.Int32>(item.InstagramUser
            
            #line default
            #line hidden
, 3673), false)
, Tuple.Create(Tuple.Create("", 3692), Tuple.Create("/", 3692), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 109 "..\..\Views\Giveaway\Giveaway.cshtml"
                                                                                                        Write(item.InstagramUser);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                                <td>");

            
            #line 110 "..\..\Views\Giveaway\Giveaway.cshtml"
                               Write(item.Comments.Length);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n");

            
            #line 112 "..\..\Views\Giveaway\Giveaway.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Giveaway\Giveaway.cshtml"
                                     foreach (var comment in item.Comments)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\Giveaway\Giveaway.cshtml"
                                   Write(comment.Comment);

            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\Giveaway\Giveaway.cshtml"
                                                        

            
            #line default
            #line hidden
WriteLiteral("                                        <br/>\r\n");

            
            #line 116 "..\..\Views\Giveaway\Giveaway.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n");

            
            #line 120 "..\..\Views\Giveaway\Giveaway.cshtml"

                            i++;
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n     " +
"   </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 130 "..\..\Views\Giveaway\Giveaway.cshtml"
 if (Model.IsActive && Model.Winner == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"testimonails\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n                        <h2><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" id=\"bannerformmodal_promo\"");

WriteLiteral(">Выбрать победителя</a></h2>\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4839), Tuple.Create("\"", 4887)
            
            #line 138 "..\..\Views\Giveaway\Giveaway.cshtml"
, Tuple.Create(Tuple.Create("", 4845), Tuple.Create<System.Object, System.Int32>(Url.Content("~/images/under-heading.png")
            
            #line default
            #line hidden
, 4845), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n    " +
"    </div>\r\n    </div>\r\n");

            
            #line 145 "..\..\Views\Giveaway\Giveaway.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"dialog\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(" />\r\n");

            
            #line 147 "..\..\Views\Giveaway\Giveaway.cshtml"

    
            
            #line default
            #line hidden
DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 149 "..\..\Views\Giveaway\Giveaway.cshtml"
   Write(Styles.Render("~/Vendor/jquery-ui/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

});

            
            #line 150 "..\..\Views\Giveaway\Giveaway.cshtml"
     

    
            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 154 "..\..\Views\Giveaway\Giveaway.cshtml"
   Write(Scripts.Render("~/Vendor/jquery-ui/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            $(function () {
                $(""#dialog"").dialog({
                    autoOpen: false,
                    modal: true,
                    title: ""Победитель"",
                    width: 600,
                    position: { my: ""center"", at: ""center"", of: window }
                });
                $(""#bannerformmodal_promo"").click(function () {
                    $.ajax({
                        type: ""POST"",
                        url: ""/giveaway/");

            
            #line 168 "..\..\Views\Giveaway\Giveaway.cshtml"
                                   Write(Model.Date);

            
            #line default
            #line hidden
WriteLiteral(@"/select"",
                        contentType: ""application/json; charset=utf-8"",
                        dataType: ""html"",
                        success: function (response) {
                            $('#dialog').html(response);
                            $('#dialog').dialog('open');
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        },
                        error: function (response) {
                            alert(response.responseText);
                        }
                    });
                });
            });
        </script>
    ");

});

            
            #line 185 "..\..\Views\Giveaway\Giveaway.cshtml"
     
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
