#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tutort.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Giveaway/Winner.cshtml")]
    public partial class _Views_Giveaway_Winner_cshtml : System.Web.Mvc.WebViewPage<Tutort.Web.ViewModels.Giveaway.GiveawayParticipantViewModel>
    {
        public _Views_Giveaway_Winner_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"heading-section\"");

WriteLiteral(">\r\n\t<h2><a");

WriteAttribute("href", Tuple.Create(" href=\"", 108), Tuple.Create("\"", 162)
, Tuple.Create(Tuple.Create("", 115), Tuple.Create("https://www.instagram.com/", 115), true)
            
            #line 4 "..\..\Views\Giveaway\Winner.cshtml"
, Tuple.Create(Tuple.Create("", 141), Tuple.Create<System.Object, System.Int32>(Model.InstagramUser
            
            #line default
            #line hidden
, 141), false)
, Tuple.Create(Tuple.Create("", 161), Tuple.Create("/", 161), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Giveaway\Winner.cshtml"
                                                                             Write(Model.InstagramUser);

            
            #line default
            #line hidden
WriteLiteral("</a></h2>\r\n\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 216), Tuple.Create("\"", 264)
            
            #line 5 "..\..\Views\Giveaway\Winner.cshtml"
, Tuple.Create(Tuple.Create("", 222), Tuple.Create<System.Object, System.Int32>(Url.Content("~/images/under-heading.png")
            
            #line default
            #line hidden
, 222), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n\t<h4>Комментарий: ");

            
            #line 6 "..\..\Views\Giveaway\Winner.cshtml"
                Write(Model.Comments.First());

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
