#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Tutort.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Page/Slider.cshtml")]
    public partial class _Views_Page_Slider_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Tutort.Web.ViewModels.Page.Slide>>
    {
        public _Views_Page_Slider_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"slider\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"flexslider\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"slides\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Page\Slider.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Page\Slider.cshtml"
             foreach (var slide in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    ");

WriteLiteral("\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 509), Tuple.Create("\"", 530)
            
            #line 17 "..\..\Views\Page\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 515), Tuple.Create<System.Object, System.Int32>(slide.ImageUrl
            
            #line default
            #line hidden
, 515), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" />\r\n                </li>\r\n");

            
            #line 19 "..\..\Views\Page\Slider.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
