//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutort.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutort.Web.Localization.Catalog", typeof(Catalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Весь ассортимент.
        /// </summary>
        public static string Catalog_All {
            get {
                return ResourceManager.GetString("Catalog_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торты.
        /// </summary>
        public static string Catalog_Cakes {
            get {
                return ResourceManager.GetString("Catalog_Cakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чизкейки.
        /// </summary>
        public static string Catalog_Cheesecakes {
            get {
                return ResourceManager.GetString("Catalog_Cheesecakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капкейки.
        /// </summary>
        public static string Catalog_Cupcakes {
            get {
                return ResourceManager.GetString("Catalog_Cupcakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чего желаете?.
        /// </summary>
        public static string Catalog_Subtitle {
            get {
                return ResourceManager.GetString("Catalog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зефир.
        /// </summary>
        public static string Catalog_Zefir {
            get {
                return ResourceManager.GetString("Catalog_Zefir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ассортимент.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
