//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutort.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutort.Web.Localization.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заславль, Фольклорная,12.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@tutort.by.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 375447531006.
        /// </summary>
        public static string ContactPhoneStrict {
            get {
                return ResourceManager.GetString("ContactPhoneStrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tutort.by.
        /// </summary>
        public static string DomainNameFull {
            get {
                return ResourceManager.GetString("DomainNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.tutort.by.
        /// </summary>
        public static string DomainNameShort {
            get {
                return ResourceManager.GetString("DomainNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fb.com/tutort.by.
        /// </summary>
        public static string Media_Facebook {
            get {
                return ResourceManager.GetString("Media_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/tutort.by/.
        /// </summary>
        public static string Media_Instagram {
            get {
                return ResourceManager.GetString("Media_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ok.ru/profile/79020679640.
        /// </summary>
        public static string Media_Odnoklassniki {
            get {
                return ResourceManager.GetString("Media_Odnoklassniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tutort.tumblr.com/.
        /// </summary>
        public static string Media_Tumblr {
            get {
                return ResourceManager.GetString("Media_Tumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/tutort_by.
        /// </summary>
        public static string Media_Twitter {
            get {
                return ResourceManager.GetString("Media_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vk.com/tutort.
        /// </summary>
        public static string Media_VK {
            get {
                return ResourceManager.GetString("Media_VK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutort.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкусное должно быть красивым.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
    }
}
