//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutort.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutort.Web.Localization.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +375 44 7531006.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звоните или пишите в Viber!.
        /// </summary>
        public static string ContactPhoneMessage {
            get {
                return ResourceManager.GetString("ContactPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ассортимент.
        /// </summary>
        public static string MainMenu_Catalog {
            get {
                return ResourceManager.GetString("MainMenu_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string MainMenu_Contacts {
            get {
                return ResourceManager.GetString("MainMenu_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розыгрыши.
        /// </summary>
        public static string MainMenu_Giveaways {
            get {
                return ResourceManager.GetString("MainMenu_Giveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainMenu_Home {
            get {
                return ResourceManager.GetString("MainMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции.
        /// </summary>
        public static string MainMenu_Offers {
            get {
                return ResourceManager.GetString("MainMenu_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукты.
        /// </summary>
        public static string MainMenu_Products {
            get {
                return ResourceManager.GetString("MainMenu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string TopMenu_AdminPanel {
            get {
                return ResourceManager.GetString("TopMenu_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий кабинет.
        /// </summary>
        public static string TopMenu_Cabinet {
            get {
                return ResourceManager.GetString("TopMenu_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string TopMenu_Home {
            get {
                return ResourceManager.GetString("TopMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string TopMenu_Login {
            get {
                return ResourceManager.GetString("TopMenu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный функционал портала доступен зарегестрированным пользователям. Для входа достаточно использовать свой аккаунт для социальных сетей (Google, VK, Facebook, Odnoklassniki).
        /// </summary>
        public static string TopMenu_Login_Alt {
            get {
                return ResourceManager.GetString("TopMenu_Login_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string TopMenu_Logout {
            get {
                return ResourceManager.GetString("TopMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой аккаунт.
        /// </summary>
        public static string TopMenu_MyAccount {
            get {
                return ResourceManager.GetString("TopMenu_MyAccount", resourceCulture);
            }
        }
    }
}
